### ISSUE TITLE
[feature] pico w support

### ISSUE THREAD

**Issue by f3bandit** [OffBroadway/cubeboot#24]
**Is your feature request related to a problem? Please describe.**
LED on the pico w is setup differently than the standard pico
…

**Describe the solution you'd like**
LED to work that same as on the standard pico, also wifi and/or bluetooth support int he future.
…

**Comment by trevor403** [comment]
This would require a change to PicoBoot so we can not make this enhancement here.
Closing in favor of your other issue https://github.com/webhdx/PicoBoot/issues/82
